import { GeneralError } from '../errorsFactory';

const catchEndThrowGetTokenError = () => {
      
}